FROM ubuntu:latest 

# Install any necessary dependencies
RUN apt-get update && apt-get install -y curl bash jq

RUN curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
RUN apt-get install gitlab-runner -y


# Copy the custom executor scripts into the container
COPY config.sh /scripts/config.sh
COPY prepare.sh /scripts/prepare.sh
COPY run.sh /scripts/run.sh
COPY cleanup.sh /scripts/cleanup.sh
# COPY config.toml /etc/gitlab-runner/config.toml

RUN chmod +x /scripts/*.sh

# # Environment variables for GitLab Runner registration
# ENV CI_SERVER_URL=https://gitlab.com/
# ENV REGISTRATION_TOKEN=glrt-y7-pLHz4dJ2ByawLLE-A
# ENV RUNNER_NAME=my-custom-runner
# ENV RUNNER_EXECUTOR=custom
# ENV RUNNER_TAG_LIST=my-tag

# # Register the runner without custom executor flags
# RUN gitlab-runner register --non-interactive \
#     --url $CI_SERVER_URL \
#     --registration-token $REGISTRATION_TOKEN \
#     --name $RUNNER_NAME \
#     --executor $RUNNER_EXECUTOR \
#     --tag-list $RUNNER_TAG_LIST

# # Start the GitLab Runner
# # CMD ["gitlab-runner", "run", "--user=gitlab-runner", "--working-directory=/home/gitlab-runner"]
# CMD /bin/bash
